[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/home/Firmiana/.local/share/qBittorrent/logs

[BitTorrent]
Session\AddTrackersEnabled=true
Session\AdditionalTrackers=http://1337.abcvg.info:80/announce\n\nhttp://bt.okmp3.ru:2710/announce\n\nhttp://ipv6.rer.lol:6969/announce\n\nhttp://nyaa.tracker.wf:7777/announce\n\nhttp://t.nyaatracker.com:80/announce\n\nhttp://t1.aag.moe:17715/announce\n\nhttp://tk.greedland.net:80/announce\n\nhttp://torrentsmd.com:8080/announce\n\nhttp://tracker.electro-torrent.pl:80/announce\n\nhttp://tracker.files.fm:6969/announce\n\nhttp://tracker.gbitt.info:80/announce\n\nhttp://tracker.mywaifu.best:6969/announce\n\nhttp://www.all4nothin.net:80/announce.php\n\nhttp://www.wareztorrent.com:80/announce\n\nhttps://tr.burnabyhighstar.com:443/announce\n\nhttps://tracker.gbitt.info:443/announce\n\nhttps://tracker.gcrenwp.top:443/announce\n\nhttps://tracker.kuroy.me:443/announce\n\nhttps://tracker.lilithraws.org:443/announce\n\nhttps://tracker.loligirl.cn:443/announce\n\nhttps://tracker.tamersunion.org:443/announce\n\nhttps://tracker.yemekyedim.com:443/announce\n\nhttps://tracker1.520.jp:443/announce\n\nhttps://trackers.mlsub.net:443/announce\n\nudp://amigacity.xyz:6969/announce\n\nudp://bt1.archive.org:6969/announce\n\nudp://bt2.archive.org:6969/announce\n\nudp://evan.im:6969/announce\n\nudp://exodus.desync.com:6969/announce\n\nudp://ipv6.fuuuuuck.com:6969/announce\n\nudp://moonburrow.club:6969/announce\n\nudp://oh.fuuuuuck.com:6969/announce\n\nudp://open.demonii.com:1337/announce\n\nudp://open.stealth.si:80/announce\n\nudp://open.tracker.ink:6969/announce\n\nudp://open.u-p.pw:6969/announce\n\nudp://opentor.org:2710/announce\n\nudp://opentracker.io:6969/announce\n\nudp://p4p.arenabg.com:1337/announce\n\nudp://retracker.lanta.me:2710/announce\n\nudp://retracker01-msk-virt.corbina.net:80/announce\n\nudp://run.publictracker.xyz:6969/announce\n\nudp://thetracker.org:80/announce\n\nudp://tracker.0x7c0.com:6969/announce\n\nudp://tracker.birkenwald.de:6969/announce\n\nudp://tracker.bittor.pw:1337/announce\n\nudp://tracker.cyberia.is:6969/announce\n\nudp://tracker.dler.com:6969/announce\n\nudp://tracker.dler.org:6969/announce\n\nudp://tracker.doko.moe:6969/announce\n\nudp://tracker.fnix.net:6969/announce\n\nudp://tracker.opentrackr.org:1337/announce\n\nudp://tracker.skyts.net:6969/announce\n\nudp://tracker.t-1.org:6969/announce\n\nudp://tracker.torrent.eu.org:451/announce\n\nudp://tracker.xor.st:6969/announce\n\nudp://tracker1.t-1.org:6969/announce\n\nudp://tracker3.t-1.org:6969/announce\n\nudp://wepzone.net:6969/announce\n\nudp://www.torrent.eu.org:451/announce\n\nudp://z.mercax.com:53/announce\n\nwss://tracker.openwebtorrent.com:443/announce
Session\DefaultSavePath=/home/Firmiana/Data
Session\ExcludedFileNames=
Session\Port=4633
Session\QueueingSystemEnabled=false

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=6

[Network]
Cookies=@Invalid()

[Preferences]
General\Locale=zh_CN
MailNotification\req_auth=true
WebUI\BanDuration=0
WebUI\LocalHostAuth=false
WebUI\Password_PBKDF2="@ByteArray(zm0b4LiMvKf3JLu/B5RViA==:D84nVwd9WvNIshUyXoOwpVMUonSrWG+Mwz/fqe8Y+eJtpmSpVR+ccnbfFTzvx1T6pW2921PmYUqMWiaICYKRsQ==)"
WebUI\Username=Firmiana

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
