wallpaper {
    monitor = DP-1
    path = ~/.config/hypr/Wallpapers/SSClub.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = ~/.config/hypr/Wallpapers/54239084_p0.png
    fit_mode = cover
}
