music_directory		"/home/Firmiana/Music/cache"
playlist_directory	"/home/Firmiana/.config/mpd/playlists"
db_file				"/home/Firmiana/.config/mpd/db"
log_file			"/home/Firmiana/.config/mpd/log"
state_file			"/home/Firmiana/.config/mpd/state"
pid_file			"/home/Firmiana/.config/mpd/pid"
user				"Firmiana"
group				"Firmiana"
bind_to_address		"127.0.0.1"
port				"6600"

audio_output {
    type        "pulse"
    name        "Headphone"
    mixer_type  "hardware"
}
